BF: fix test error on Python 3
Numpy does not implement the `__round__` method, causing the following
error when trying to use builtin `round`:

    >>> round(np.array([1]))
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    TypeError: type numpy.ndarray doesn't define __round__ method

For the test error in dipy, see:
https://travis-ci.org/MacPython/dipy-wheels/jobs/140257955#L357

Use numpy's `assert_almost_equal` instead of the version from nose, to
avoid this problem.