DOC: Add missing description to parameters across methods
Add missing description to parameters across miscellaneous methods.

Fixes:
```
/dipy/reconst/csdeconv.py:docstring of dipy.reconst.csdeconv.auto_response:12:
 ERROR: Unexpected indentation.
/dipy/reconst/csdeconv.py:docstring of dipy.reconst.csdeconv.auto_response:9:
 WARNING: Block quote ends without a blank line; unexpected unindent.
```

and similar errors raised for example in:
https://github.com/dipy/dipy/actions/runs/10269802236/job/28416082327#step:5:1015