NF: Build using NumPy 2.0.0
Build using NumPy 2.0.0 so that Cython code can be correctly compiled
while supporting both NumPy 1.x and 2.x.

Fixes:
```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
```

and
```
ERROR align/__init__.py -
 ImportError: numpy.core.multiarray failed to import
 (auto-generated because you didn't call 'numpy.import_array()' after
 cimporting numpy; use '<void>numpy._import_array' to disable if you
 are certain you don't need it).
```

raised for example at:
https://github.com/dipy/dipy/actions/runs/9551350677/job/26325486880#step:10:43
and
https://github.com/dipy/dipy/actions/runs/9551350677/job/26325486880#step:10:17819