DOC: Enclose absolute value math expression within LaTeX markup
Enclose absolute value math expression within LaTeX markup: vertical
bars are used in reStructuredText as a marker for a substitution,
whereas in this case they were intended to mean absolute value.

Fixes:
```
/dipy/align/streamlinear.py:docstring of dipy.align.streamlinear.StreamlineDistanceMetric.__init__:9:
 ERROR: Undefined substitution referenced: "num_threads + 1".
```

and similar errors raised for example in:
https://github.com/dipy/dipy/actions/runs/10269802236/job/28416082327#step:5:818