STYLE: Prefer using `np.asarray` to avoid copy while creating an array
Prefer using `np.asarray` to avoid copy while creating an array in
preparation for full NumPy 2.0 compatibility.

Fixes:
```
FAILED core/tests/test_interpolation.py::test_TriLinearInterpolator -
 ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)`
 to allow a copy when needed (no behavior change in NumPy 1.x).
```

raised for example in:
https://github.com/dipy/dipy/actions/runs/9605741685/job/26493943578?pr=3266#step:10:7997