BF: improves the TrackerStatus enum management to avoid the error below:
```
==================================== ERRORS ====================================
_____ ERROR collecting tracking/tests/test_propspeed.cpython-310-darwin.so _____
../venv/lib/python3.10/site-packages/dipy/conftest.py:76: in collect
    mod = importlib.import_module(mod_name)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:1184: in exec_module
    ???
<frozen importlib._bootstrap>:241: in _call_with_frames_removed
    ???
dipy/tracking/tests/test_propspeed.pyx:21: in init dipy.tracking.tests.test_propspeed
    ???
E   ImportError: cannot import name FAIL

The above exception was the direct cause of the following exception:
../venv/lib/python3.10/site-packages/dipy/conftest.py:86: in collect
    raise PyxException(msg, self.path, 0) from e
E   dipy.conftest.PyxException: ('Import failed for /Users/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/dipy/tracking/tests/test_propspeed.cpython-310-darwin.so. Make sure you cython file has been compiled.', PosixPath('/Users/runner/work/dipy/dipy/venv/lib/python3.10/site-packages/dipy/tracking/tests/test_propspeed.cpython-310-darwin.so'), 0)
```