NF: Call `cnp.import_array()` explicitly to use the NumPy C API
Call `cnp.import_array()` explicitly to use the NumPy C API: Cython
modules (or anything using the NumPy C API) must call
`cnp.import_array()` to import the NumPy C API.

Fixes:
```
  File "vector_fields.pyx", line 1, in init dipy.align.vector_fields
ImportError: numpy.core.multiarray failed to import
 (auto-generated because you didn't call 'numpy.import_array()' after
 cimporting numpy; use '<void>numpy._import_array' to disable if you
 are certain you don't need it).
```

reported by third-party tool (e.g. MNE) maintaners when testing their
tools with NumPy 2.0.