STYLE: Fix typo in view parameter `sagital`
Fix typo in view parameter `sagital`. Warn about future removal of
support.

Fixes:
```
Error: ./dipy/viz/streamline.py:10: sagital ==> sagittal
Error: ./dipy/viz/streamline.py:45: sagital ==> sagittal
Error: ./dipy/viz/tests/test_streamline.py:34: sagital ==> sagittal
```

raised for example in:
https://github.com/dipy/dipy/actions/runs/9051840842/job/24868829333?pr=3216#step:4:17

`codespell` does not allow for now inline ignore rules, so add `sagital`
to the whitelist to allow the spell check to pass. The word will be
removed as soon as a new `codespell` version gets released.

Take advantage of the commit to remove the default value from the
docstring and rely on the method signature to remove the maintenance
burden.