BUG: Fix workflows IO `FetchFlow``all` dataset fetching
Fix workflows IO `FetchFlow` `all` dataset fetching: the `fetch_data` is
contained in the `available_data` dictionary because as the actual data fetcher
function it starts with  `fetch_`. However, the `fetch_data` function is what
the actual fetchers call with the necessary arguments. Thus, the
`dipy.workflows.tests.test_io.test_io_fetch` test fails if we specify
`fetch_flow.run(['all'])` because the parameters of `fetch_data` are empty.

The fix is to avoid adding the `fetch_data` function when the dictionary is
created.

Fixes
```
  File
"/home/local/USHERBROOKE/legj1809/src/dipy/dipy/workflows/tests/test_io.py",
line 80, in <module>
    test_io_fetch()
  File
"/home/local/USHERBROOKE/legj1809/src/dipy/dipy/workflows/tests/test_io.py",
line 54, in test_io_fetch
    fetch_flow.run(['all'])
  File "/home/local/USHERBROOKE/legj1809/src/dipy/dipy/workflows/io.py", line
172, in run
    fetcher_function()
TypeError: fetch_data() missing 2 required positional arguments: 'files' and
'folder'
```

Add a test for the `all` case and compare to the expected number of dataset
folders (18).