DOC: Add missing whitespace between link text and less-than sign
Add missing whitespace between the link text and the less-than sign
opening the target URL.

Fixes:
```
/dipy/dipy/doc/devel/benchmarking.rst::
 ERROR: Anonymous hyperlink mismatch: 1 references but 0 targets.
See "backrefs" attribute for IDs.
```

raised for example at:
https://github.com/dipy/dipy/actions/runs/10641220263/job/29502086246#step:5:688